import Head from 'next/head';
import { ReactNode } from 'react';
import { NavBar } from './';
import styles from '../styles/layout.module.css';

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Student Pickup App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className={styles.main}>{children}</div>
    </>
  );
};
